#!/bin/bash
set -euo pipefail

VERSION="0.2.3"

CONFIG_DIR="${HOME}/.config/nattoujam/ps1"
PRESETS="${CONFIG_DIR}/presets"
CURRENT="${CONFIG_DIR}/current"
HELPERS="${CONFIG_DIR}/helpers"
STATE="${CONFIG_DIR}/state"

current_shell() {
  if [[ "${SHELL:-}" == *zsh ]]; then
    echo zsh
  else
    echo bash
  fi
}

current_preset() {
  if [[ -f "$STATE" ]]; then
    tr -d '[:space:]' < "$STATE"
  fi
}

cmd_list() {
  local shell current name marker
  shell=$(current_shell)
  current=$(current_preset)
  while IFS= read -r name; do
    if [[ "$name" == "$current" ]]; then
      marker='*'
    else
      marker=' '
    fi
    echo "$marker $name"
  done < <(grep "^${shell}\\." "$PRESETS" | sed 's/^[^.]*\.//' | cut -d= -f1 | sort)
}

cmd_set() {
  local name="$1"
  local shell var_name line value tmp
  shell=$(current_shell)
  if [[ "$shell" == zsh ]]; then
    var_name=PROMPT
  else
    var_name=PS1
  fi

  line=$(grep "^${shell}\\.${name}=" "$PRESETS" || true)
  if [[ -z "$line" ]]; then
    echo "ps1: preset '${name}' not found for ${shell}" >&2
    exit 1
  fi
  value=${line#*=}

  tmp="${CURRENT}.tmp"
  {
    echo "# generated by ps1 - do not edit manually"
    if [[ -f "$HELPERS" ]]; then
      echo "source ${HELPERS}"
    fi
    echo "${var_name}='${value} '"
  } > "$tmp"
  mv "$tmp" "$CURRENT"

  echo -n "$name" > "$STATE"
  echo "ps1: switched to '${name}'"
  echo "run 'source ~/.zshrc' or 'source ~/.bashrc' to apply"
}

cmd_help() {
  echo "ps1 ${VERSION}"
  echo ""
  echo "usage: ps1 <command>"
  echo ""
  echo "commands:"
  echo "  list           list available presets"
  echo "  set <name>     switch to preset"
  echo "  help           show this help"
}

main() {
  if [[ ! -f "$PRESETS" ]]; then
    echo "ps1: config not found: ${PRESETS}" >&2
    exit 1
  fi

  local cmd="${1:-help}"
  case "$cmd" in
    list) cmd_list ;;
    set)
      if [[ $# -lt 2 ]]; then
        echo "usage: ps1 set <name>" >&2
        exit 1
      fi
      cmd_set "$2"
      ;;
    help) cmd_help ;;
    *)
      echo "ps1: unknown command '${cmd}'" >&2
      echo "run 'ps1 help' for usage" >&2
      exit 1
      ;;
  esac
}

main "$@"
