import std/[os, strutils, tables, sequtils, algorithm]

const
  Version     = "0.2.0"
  ConfigDir   = "~/.config/nattoujam/ps1"
  PresetsConf = ConfigDir / "presets"
  CurrentSh   = ConfigDir / "current"
  Helperssh   = ConfigDir / "helpers"
  StateFile   = ConfigDir / "state"

type
  Presets = Table[string, Table[string, string]]

proc currentShell(): string =
  result = if getEnv("SHELL").endsWith("zsh"): "zsh" else: "bash"

proc parsePresets(path: string): Presets =
  result = initTable[string, Table[string, string]]()
  for line in lines(path):
    let stripped = line.strip()
    if stripped.startsWith("#") or stripped.len == 0:
      continue
    let eqIdx = stripped.find('=')
    if eqIdx < 0:
      continue
    let key   = stripped[0 ..< eqIdx]
    let value = stripped[eqIdx + 1 .. ^1]
    let parts = key.split('.')
    if parts.len != 2:
      continue
    let shell = parts[0]
    let name  = parts[1]
    if shell notin result:
      result[shell] = initTable[string, string]()
    result[shell][name] = value

proc presetNames(presets: Presets): seq[string] =
  let shell = currentShell()
  if shell in presets:
    result = toSeq(presets[shell].keys).sorted()

proc currentPreset(): string =
  let statePath = expandTilde(StateFile)
  result = if fileExists(statePath): readFile(statePath).strip() else: ""

proc cmdList(presets: Presets) =
  let current = currentPreset()
  for i, name in presetNames(presets):
    let marker = if name == current: "*" else: " "
    echo marker & ' ' & name

proc cmdSet(presets: Presets, name: string) =
  let shell   = currentShell()
  let varName = if shell == "zsh": "PROMPT" else: "PS1"

  if shell notin presets or name notin presets[shell]:
    stderr.writeLine("ps1: preset '" & name & "' not found for " & shell)
    quit(1)

  let value     = presets[shell][name]
  let outPath   = expandTilde(CurrentSh)
  let statePath = expandTilde(StateFile)
  let helpersPath = expandTilde(Helperssh)

  var content = "# generated by ps1 - do not edit manually\n"
  if fileExists(helpersPath):
    content &= "source " & helpersPath & "\n"
  content &= varName & "='" & value & " '\n"

  writeFile(outPath, content)
  writeFile(statePath, name)
  echo "ps1: switched to '" & name & "'"
  echo "run 'source ~/.zshrc' or 'source ~/.bashrc' to apply"

proc main() =
  let confPath = expandTilde(PresetsConf)
  if not fileExists(confPath):
    stderr.writeLine("ps1: config not found: " & confPath)
    quit(1)

  let presets = parsePresets(confPath)
  let args    = commandLineParams()
  let cmd     = if args.len > 0: args[0] else: "help"

  case cmd
  of "list":
    cmdList(presets)
  of "set":
    if args.len < 2:
      stderr.writeLine("usage: ps1 set <name>")
      quit(1)
    cmdSet(presets, args[1])
  of "help":
    echo "ps1 " & Version
    echo ""
    echo "usage: ps1 <command>"
    echo ""
    echo "commands:"
    echo "  list           list available presets"
    echo "  set <name>     switch to preset"
    echo "  help           show this help"
  else:
    stderr.writeLine("ps1: unknown command '" & cmd & "'")
    stderr.writeLine("run 'ps1 help' for usage")
    quit(1)

main()
